---
- name: Remove all htpasswd files. This makes sure they are clear, and can later be recreated correctly.
  file:
    state: absent
    path: "{{ item.location }}/"
  when: "htpasswd is defined"
  loop: "{{ htpasswd }}"

- name: Create htpasswd files with entries
  htpasswd:
    path: "{{ item.0.location }}"
    name: "{{ item.1.name }}"
    password: "{{ item.1.passphrase }}"
  when: "htpasswd is defined"
  with_subelements:
  - "{{ htpasswd }}"
  - "secrets"

- name: Copy ssh private key
  copy:
    src: files/ssh/id_rsa_docker
    dest: /root/id_rsa_docker
    owner: "1000"
    group: "1000"
    mode: "0600"